<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Public Page
Route::get('/', function () {
    return view('welcome');
});

// Auth Routes (Login/Register) generated by Laravel UI
Auth::routes(['verify' => true]);

// --- LOGGED IN USERS ONLY ---
Route::middleware(['auth', 'verified'])->group(function () {

    // 1. Standard User Dashboard
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])
        ->name('dashboard');

    // 2. Admin Dashboard
    // URL: localhost/admin/dashboard
    Route::get('/admin/dashboard', function () {
        return view('admin.dashboard');
    })->name('admin.dashboard');
    Route::get('/upload', [App\Http\Controllers\FileUploadController::class, 'create'])->name('upload.create');
    Route::post('/upload', [App\Http\Controllers\FileUploadController::class, 'store'])->name('upload.store');
    Route::get('/download/{slug}', [App\Http\Controllers\DownloadController::class, 'download'])
        ->name('file.download');
});

Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/admin/dashboard', function () {
        return view('admin.dashboard');
    })->name('admin.dashboard');
});

?>