<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Public Page
Route::get('/', function () {
    return view('layouts.app');
});

// Auth Routes (Login/Register) generated by Laravel UI
Auth::routes(['verify' => true]);

// --- LOGGED IN USERS ONLY ---
Route::middleware(['auth', 'verified'])->group(function () {

    // 1. Standard User Dashboard
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])
        ->name('dashboard');


    Route::delete('/file/{id}', [App\Http\Controllers\FileUploadController::class, 'destroy'])
        ->name('file.destroy');


    Route::get('/upload', [App\Http\Controllers\FileUploadController::class, 'create'])->name('upload.create');
    Route::post('/upload', [App\Http\Controllers\FileUploadController::class, 'store'])->name('upload.store');


    Route::get('/download/{slug}', [App\Http\Controllers\DownloadController::class, 'download'])
        ->name('file.download');


    Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'show'])->name('profile.show');
});

Route::middleware(['auth', 'role:admin'])->prefix('admin')->group(function () {
    Route::get('/admin/dashboard', function () {
        return view('admin.dashboard');
    })->name('admin.dashboard');

    Route::delete('/file/{id}', [App\Http\Controllers\AdminController::class, 'deleteFile'])
        ->name('admin.file.delete');


    Route::get('/admin/dashboard', [App\Http\Controllers\AdminController::class, 'index'])
        ->name('admin.dashboard');


    Route::post('/user/{id}/toggle', [App\Http\Controllers\AdminController::class, 'toggleUserStatus'])
        ->name('admin.user.toggle');
});

?>